# Generated by Django 4.0.3 on 2022-05-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription',
            new_name='description',
        ),
    ]
